Document: editeuruniversel
Title: Debian editeuruniversel Manual
Author: <insert document author here>
Abstract: This manual describes what editeuruniversel is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/editeuruniversel/editeuruniversel.sgml.gz

Format: postscript
Files: /usr/share/doc/editeuruniversel/editeuruniversel.ps.gz

Format: text
Files: /usr/share/doc/editeuruniversel/editeuruniversel.text.gz

Format: HTML
Index: /usr/share/doc/editeuruniversel/html/index.html
Files: /usr/share/doc/editeuruniversel/html/*.html
